# Generated by Django 4.2.6 on 2023-10-27 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_reviewbuku_wishlistbuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistbuku',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlistbuku',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
