# Generated by Django 4.2.6 on 2023-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlistbuku_date_added_wishlistbuku_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistbuku',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
