# Generated by Django 4.2.6 on 2023-10-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_wishlistbuku_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistbuku',
            name='image',
        ),
    ]
