# Generated by Django 4.2.4 on 2023-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_remove_wishlistbuku_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistbuku',
            name='is_from_wishlist',
            field=models.BooleanField(default=True),
        ),
    ]
