# Generated by Django 4.2.4 on 2023-10-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_wishlistbuku_is_from_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistbuku',
            name='is_from_wishlist',
        ),
    ]
