# Generated by Django 4.2.6 on 2023-10-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231028_1516'),
        ('YourBook', '0003_pinjambuku_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjambuku',
            name='buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.buku'),
            preserve_default=False,
        ),
    ]
