# Generated by Django 4.2.6 on 2023-10-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourBook', '0004_pinjambuku_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjambuku',
            name='judul_buku',
            field=models.TextField(),
        ),
    ]
