# Generated by Django 4.2.6 on 2023-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourBook', '0005_alter_pinjambuku_judul_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjambuku',
            name='judul_buku',
            field=models.CharField(max_length=255),
        ),
    ]
