# Generated by Django 4.2.6 on 2023-10-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_buku_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='bookmarked',
        ),
    ]
