# Generated by Django 4.2.6 on 2023-10-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_remove_buku_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='language',
        ),
    ]
