# Generated by Django 4.2.6 on 2023-12-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Type', models.TextField(blank=True, null=True)),
                ('Issued', models.TextField(blank=True, null=True)),
                ('Title', models.TextField(blank=True, null=True)),
                ('Language', models.TextField(blank=True, null=True)),
                ('Authors', models.TextField(blank=True, null=True)),
                ('Subjects', models.TextField(blank=True, null=True)),
                ('LoCC', models.TextField(blank=True, null=True)),
                ('Bookshelves', models.TextField(default='Cookbooks and Cooking')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
