# Generated by Django 4.2.6 on 2023-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='description',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='language',
        ),
        migrations.AddField(
            model_name='buku',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='bookshelves',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='locc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='text',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
