# Generated by Django 4.2.6 on 2023-10-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_buku_description_remove_buku_language_and_more'),
    ]

    operations = [
        
    ]
