# Generated by Django 4.2.6 on 2023-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231028_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='author',
            new_name='Authors',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='bookshelves',
            new_name='Bookshelves',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='issue',
            new_name='Issued',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='lang',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='locc',
            new_name='LoCC',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='subject',
            new_name='Subjects',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='text',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='type',
            new_name='Type',
        ),
    ]
