# Generated by Django 4.2.6 on 2023-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_author_buku_authors_and_more'),
    ]

    operations = [
    ]
