# Generated by Django 4.2.6 on 2023-10-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231029_1236'),
        ('main', '0008_alter_user_user'),
    ]

    operations = [
    ]
