# Generated by Django 4.2.6 on 2023-10-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_buku_authors_alter_buku_bookshelves_and_more'),
    ]

    operations = [
    ]
