# Generated by Django 4.2.6 on 2023-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_0002_auto_20231029_1236_0008_alter_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='user',
        ),
        migrations.AlterField(
            model_name='buku',
            name='Authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Bookshelves',
            field=models.CharField(default='Cookbooks and Cooking', max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Issued',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='LoCC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
