# Generated by Django 4.2.6 on 2023-10-29 15:25

from django.db import migrations
from django.core.management import call_command
def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "main/fixtures/books.json")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_buku_user_alter_buku_authors_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data)
    ]
