# Generated by Django 4.2.6 on 2023-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20231029_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='Bookshelves',
            field=models.CharField(default='Cookbooks and Cooking', max_length=255),
        ),
    ]
