# Generated by Django 4.2.6 on 2023-12-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('issued', models.DateField(auto_now_add=True, null=True)),
                ('subjects', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('bookshelves', models.TextField(default='Cookbooks and Cooking')),
                ('locc', models.TextField(default='TX')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
