# Generated by Django 4.2.6 on 2023-10-29 00:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_buku_authors_alter_buku_bookshelves_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_book_book_book_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Publication',
        ),
    ]
