# Generated by Django 4.2.6 on 2023-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_book_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.AddField(
            model_name='publication',
            name='bookshelves',
            field=models.CharField(default='Cookbooks and Cooking', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='subjects',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
